CLEARSCREEN.
WAIT 0.5.
set tgt to MUN.
PRINT ENCOUNTER.
PRINT ENCOUNTER:NAME.
PRINT ENCOUNTER:BODY.
PRINT ENCOUNTER:BODY:RADIUS.
PRINT ENCOUNTER:PERIAPSIS.

if ENCOUNTER:BODY = tgt {PRINT "Found".}.

set X to NEXTNODE.
PRINT X:ORBIT:PERIAPSIS.
PRINT X:ORBIT:APOAPSIS.
PRINT X:ORBIT:BODY.

PRINT tgt:OBT:PERIAPSIS.
PRINT tgt:OBT:APOAPSIS.
PRINT tgt:RADIUS.

